name: Aria2-CI

on:
  push:
    branches: 
      - master
      
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                ref: master

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'

            - name: Build
              run: |
                mkdir -p ./targets
                cd ./targets
                git clone https://github.com/ziahamza/webui-aria2.git
                cd webui-aria2
                npm install

            - name: Deploy
              run: |
                cd ./targets
                tar czvf aria2.tar.gz webui-aria2
                rm -rf webui-aria2

            - name: Upload
              uses: actions/upload-artifact@master
              with:
                name: webui-aria2
                path: ./targets/
